name: configuration
description: The module configuration
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  get: ^4.3.6

  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  connectivity: ^3.0.6
  permission_handler: ^9.2.0
  device_info: ^2.0.2
  package_info: ^2.0.2
  flutter_keychain: ^2.0.1
  logger: ^1.1.0
  flutter_screenutil: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.tn.configuration
    iosBundleIdentifier: com.tn.configuration
flutter_intl:
  enabled: true
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en

  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/flutter-localization-workflow
    project_id: # Configured manually or through 'Connect to Localizely' command. Get it from the https://app.localizely.com/projects pages.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false